#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

npx lint-staged

echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'